let  cards = [
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'apple',reward: 2, penalty: 2, location: 'piles', trashing: false, loading: false },

  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'cheese',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },

  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'bread',reward: 3, penalty: 2, location: 'piles', trashing: false, loading: false },

  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },
  {type:'legal',name: 'chicken',reward: 4, penalty: 2, location: 'piles', trashing: false, loading: false },

  {type:'illegal',name: 'pepper',reward: 6, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'pepper',reward: 6, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'pepper',reward: 6, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'pepper',reward: 6, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'pepper',reward: 6, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'pepper',reward: 6, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'pepper',reward: 6, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'pepper',reward: 6, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'pepper',reward: 6, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'pepper',reward: 6, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'pepper',reward: 6, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'pepper',reward: 6, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'pepper',reward: 6, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'pepper',reward: 6, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'pepper',reward: 6, penalty: 4, location: 'piles', trashing: false, loading: false },

  {type:'illegal',name: 'liquor',reward: 7, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'liquor',reward: 7, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'liquor',reward: 7, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'liquor',reward: 7, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'liquor',reward: 7, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'liquor',reward: 7, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'liquor',reward: 7, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'liquor',reward: 7, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'liquor',reward: 7, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'liquor',reward: 7, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'liquor',reward: 7, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'liquor',reward: 7, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'liquor',reward: 7, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'liquor',reward: 7, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'liquor',reward: 7, penalty: 4, location: 'piles', trashing: false, loading: false },

  {type:'illegal',name: 'silk',reward: 8, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'silk',reward: 8, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'silk',reward: 8, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'silk',reward: 8, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'silk',reward: 8, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'silk',reward: 8, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'silk',reward: 8, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'silk',reward: 8, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'silk',reward: 8, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'silk',reward: 8, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'silk',reward: 8, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'silk',reward: 8, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'silk',reward: 8, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'silk',reward: 8, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'silk',reward: 8, penalty: 4, location: 'piles', trashing: false, loading: false },

  {type:'illegal',name: 'crossbow',reward: 9, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'crossbow',reward: 9, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'crossbow',reward: 9, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'crossbow',reward: 9, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'crossbow',reward: 9, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'crossbow',reward: 9, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'crossbow',reward: 9, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'crossbow',reward: 9, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'crossbow',reward: 9, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'crossbow',reward: 9, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'crossbow',reward: 9, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'crossbow',reward: 9, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'crossbow',reward: 9, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'crossbow',reward: 9, penalty: 4, location: 'piles', trashing: false, loading: false },
  {type:'illegal',name: 'crossbow',reward: 9, penalty: 4, location: 'piles', trashing: false, loading: false },


  



  





  

  
  
]

for(let i in cards){
  i = parseInt(i)
  cards[i].index = i
}



export {cards}